/**
 * svelte-pdf Vite Plugin
 *
 * Enables importing *.pdf.svelte files as modules that export render():
 *
 *   import { render } from './Invoice.pdf.svelte';
 *   const pdf = await render({ invoice });
 *   pdf.pipe(res);
 *
 * ─── How it works ────────────────────────────────────────────────────────────
 *
 * The plugin hooks into Vite's module resolution pipeline at two points:
 *
 * 1. resolveId  — When Vite sees an import ending in .pdf.svelte, we redirect
 *                 it to a virtual module ID (prefixed with \0svelte-pdf:).
 *                 The \0 prefix is the Rollup/Vite convention meaning "virtual
 *                 module — other plugins must not touch this ID".
 *                 This prevents @sveltejs/vite-plugin-svelte from also
 *                 processing the file as a normal Svelte component.
 *
 * 2. load       — When Vite asks for the content of the virtual module, we:
 *                   a) Read the original .pdf.svelte file from disk
 *                   b) Compile it with the Svelte compiler (generate: 'server')
 *                   c) Wrap the compiled component with the render() pipeline
 *                   d) Return the final JS module
 *
 * ─── Output shape ────────────────────────────────────────────────────────────
 *
 * The generated module looks roughly like:
 *
 *   // --- Svelte-compiled component (SSR) ---
 *   import * as $ from 'svelte/internal/server';
 *   function Invoice($$renderer, $$props) { ... }
 *
 *   // --- svelte-pdf render wrapper (injected by this plugin) ---
 *   import { render as __svelteRender } from 'svelte/server';
 *   import { createDocument } from 'svelte-pdf/runtime/document.js';
 *   // ... other runtime imports ...
 *
 *   export async function render(props = {}) {
 *     const doc = createDocument();
 *     const { html: _ } = __svelteRender(Invoice, { props, context: ... });
 *     await loadResources(doc.resources);
 *     computeLayout(doc);
 *     return renderPDF(paginate(doc));
 *   }
 */

import { compile } from 'svelte/compiler';
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';

// ─── Constants ───────────────────────────────────────────────────────────────

/**
 * Content written to the companion `.d.ts` file alongside each `.pdf.svelte`.
 *
 * This concrete file-level declaration takes precedence over both the
 * svelte2tsx-generated `.d.ts` (which only has a `default` component export)
 * and the ambient wildcard `declare module '*.pdf.svelte'` in pdf-svelte.d.ts,
 * giving TypeScript the correct `render()` signature for every template.
 *
 * The content is a static string so it is deterministic — repeated writes
 * always produce the same bytes, which means the file is never re-written
 * after the first emission (no dirty git state on clean rebuilds).
 */
const DTS_CONTENT =
	`// AUTO-GENERATED by svelte-pdf – do not edit.\n` +
	`// This file overrides the svelte2tsx-generated declaration to expose\n` +
	`// the render() function that the svelte-pdf Vite plugin injects at runtime.\n` +
	`import type { Readable } from 'node:stream';\n` +
	`export declare function render(props?: Record<string, any>): Promise<Readable>;\n`;

/**
 * Virtual module prefix.
 *
 * Rollup and Vite treat any module ID starting with \0 as virtual —
 * meaning it has no corresponding file on disk (from their perspective)
 * and other plugins will not attempt to resolve or load it.
 *
 * We append the absolute file path so the load hook knows which file to read.
 * Example: \0svelte-pdf:/home/user/project/src/Invoice.pdf.svelte
 */
const VIRTUAL_PREFIX = '\0svelte-pdf:';

// ─── Plugin ──────────────────────────────────────────────────────────────────

/**
 * Project root, stored in configResolved so buildStart and configureServer
 * can scan for .pdf.svelte files without needing it passed as a parameter.
 */
let projectRoot = process.cwd();

export function sveltePDF(): Plugin {
	return {
		name: 'svelte-pdf',

		// enforce: 'pre' makes this plugin run before @sveltejs/vite-plugin-svelte.
		// Without this, the Svelte plugin would intercept .pdf.svelte files first
		// and try to compile them as regular Svelte UI components, which would fail
		// because our resolveId hook hasn't had a chance to redirect them yet.
		enforce: 'pre',

		// ── configResolved ─────────────────────────────────────────────────────
		//
		// Store the resolved project root so later hooks can scan the filesystem
		// without it being passed in manually.
		configResolved(config: ResolvedConfig) {
			projectRoot = config.root;
		},

		// ── configureServer ────────────────────────────────────────────────────
		//
		// Fires during dev server setup, before any requests arrive and before
		// the language server makes its first pass over source files.
		// Emitting .d.ts files here ensures they exist when the TS language
		// server indexes the project on startup.
		configureServer() {
			for (const filePath of walkForPdfSvelte(projectRoot)) {
				emitDts(filePath);
			}
		},

		// ── buildStart ─────────────────────────────────────────────────────────
		//
		// Fires at the start of every Rollup/Vite build pass, including
		// `vite build` and `pnpm package`. Ensures companion .d.ts files are
		// present for every .pdf.svelte in the project before bundling begins.
		buildStart() {
			for (const filePath of walkForPdfSvelte(projectRoot)) {
				emitDts(filePath);
			}
		},

		// ── resolveId ──────────────────────────────────────────────────────────
		//
		// Called whenever Vite resolves an import statement.
		// id       = the raw import string, e.g. './Invoice.pdf.svelte'
		// importer = the file that contains the import statement
		//
		// This hook does two things:
		//
		//  A) For .pdf.svelte imports → redirect to a virtual module ID.
		//
		//  B) For ANY relative import from within one of our virtual modules
		//     (i.e. when importer starts with VIRTUAL_PREFIX) → resolve the
		//     path relative to the real source file.
		//
		//     This is necessary because the Svelte compiler preserves the
		//     import statements from the <script> block verbatim (e.g.
		//     `import Page from '../components/Page/Page.svelte'`). When
		//     Vite later tries to resolve those relative paths it uses the
		//     module's registered ID as the base. Since our virtual IDs start
		//     with \0svelte-pdf: Vite has no real path to resolve against,
		//     so relative resolution fails.
		//
		//     Solution: when the importer is one of our virtual modules we
		//     strip the prefix to recover the real file path and use that
		//     as the base for relative resolution.
		resolveId(id: string, importer?: string) {
			// ── B: resolve relative imports that come FROM our virtual modules ──
			//
			// The generated module (virtual ID = \0svelte-pdf:/abs/path/file.pdf)
			// contains the Svelte-compiled code which preserves the original relative
			// imports. We must resolve those ourselves so Vite can load them.
			if (importer?.startsWith(VIRTUAL_PREFIX)) {
				// Add .svelte back to recover the real source path.
				const realImporter = importer.slice(VIRTUAL_PREFIX.length) + '.svelte';

				if (id.startsWith('./') || id.startsWith('../')) {
					const absolutePath = resolve(dirname(realImporter), id);

					// If the resolved file is itself a .pdf.svelte, wrap it too.
					if (absolutePath.endsWith('.pdf.svelte')) {
						return VIRTUAL_PREFIX + absolutePath.slice(0, -'.svelte'.length);
					}

					// The Svelte compiler preserves imports with their original extensions,
					// but TypeScript source files use .ts on disk while imports reference
					// .js (the JS output convention). When the resolved .js path does not
					// exist, fall back to .ts so Vite can load the TypeScript source.
					if (absolutePath.endsWith('.js') && !existsSync(absolutePath)) {
						const tsPath = absolutePath.slice(0, -3) + '.ts';
						if (existsSync(tsPath)) return tsPath;
					}

					// Otherwise return the absolute path so Vite can find it on disk.
					return absolutePath;
				}
			}

			// ── A: intercept .pdf.svelte imports ───────────────────────────────
			if (!id.endsWith('.pdf.svelte')) return null;

			const absolutePath = importer ? resolve(dirname(importer), id) : resolve(id);

			// Strip .svelte from the virtual ID so it contains no .svelte substring.
			// vite-plugin-svelte has two hooks — `compile` and `compile-module` —
			// that both match on .svelte in the module ID. Stripping it prevents
			// either hook from touching our already-compiled JS output.
			return VIRTUAL_PREFIX + absolutePath.slice(0, -'.svelte'.length);
		},

		// ── load ───────────────────────────────────────────────────────────────
		//
		// Called when Vite needs the source code for a module.
		// For virtual modules we return the code directly instead of reading
		// from the filesystem (even though we do read the original .pdf.svelte
		// file — we just don't tell Vite that this ID corresponds to that file).
		load(id: string) {
			if (!id.startsWith(VIRTUAL_PREFIX)) return null;

			// Add .svelte back — resolveId stripped it to avoid vite-plugin-svelte.
			const filePath = id.slice(VIRTUAL_PREFIX.length) + '.svelte';

			// Read the .pdf.svelte source from disk.
			const source = readFileSync(filePath, 'utf-8');

			// Register the file as a watch dependency.
			// When the .pdf.svelte file changes on disk, Vite will invalidate
			// the virtual module and trigger a rebuild / HMR update.
			this.addWatchFile(filePath);

			// Compile the Svelte component for server-side rendering.
			//
			// generate: 'server' produces a function-based component that
			// writes to a renderer (not the DOM). This is what we need because
			// svelte-pdf never runs in a browser — it runs server-side to build
			// the PDF AST via getContext/setContext side effects.
			const compiled = compile(source, {
				filename: filePath,
				generate: 'server'
			});

			// Forward any Svelte compiler warnings to Vite's warning system
			// so they show up in the terminal during development.
			for (const warning of compiled.warnings) {
				this.warn(warning.message);
			}

			// Emit the companion .d.ts so the TypeScript language server sees
			// the correct render() signature for this specific file.
			// This covers files created after server startup that were missed
			// by the buildStart / configureServer proactive scans.
			emitDts(filePath);

			// Produce the final module code: compiled component + render wrapper.
			return buildRenderWrapper(compiled.js.code, filePath);
		}
	};
}

// ─── .d.ts helpers ───────────────────────────────────────────────────────────

/**
 * Writes a companion `.d.ts` alongside a `.pdf.svelte` source file.
 *
 * The write is idempotent: if the file already exists with identical content
 * it is not touched, so clean rebuilds do not produce dirty git state.
 *
 * @param sourceFilePath - Absolute path to the `.pdf.svelte` file
 */
function emitDts(sourceFilePath: string): void {
	const dtsPath = sourceFilePath + '.d.ts';
	let existing: string | null = null;
	try {
		existing = readFileSync(dtsPath, 'utf-8');
	} catch {
		// File does not exist yet — proceed to write.
	}
	if (existing === DTS_CONTENT) return;
	writeFileSync(dtsPath, DTS_CONTENT, 'utf-8');
}

/**
 * Recursively finds all `.pdf.svelte` files under `dir`.
 *
 * Skips `node_modules` directories to avoid scanning installed packages.
 *
 * @param dir - Directory to search
 * @returns Absolute paths of every `.pdf.svelte` file found
 */
function walkForPdfSvelte(dir: string): string[] {
	const results: string[] = [];
	let entries;
	try {
		entries = readdirSync(dir, { withFileTypes: true });
	} catch {
		return results;
	}
	for (const entry of entries) {
		if (entry.isDirectory()) {
			if (entry.name === 'node_modules') continue;
			results.push(...walkForPdfSvelte(resolve(dir, entry.name)));
		} else if (entry.name.endsWith('.pdf.svelte')) {
			results.push(resolve(dir, entry.name));
		}
	}
	return results;
}

// ─── Code generation ─────────────────────────────────────────────────────────

/**
 * Wraps compiled Svelte SSR component code with the svelte-pdf render pipeline.
 *
 * @param compiledCode - The JS output from svelte/compiler with generate:'server'
 * @param filePath     - Source file path (used in comments for traceability)
 * @returns A complete JS module string that exports render()
 *
 * The Svelte compiler produces code like:
 *
 *   import * as $ from 'svelte/internal/server';
 *   export default function Invoice($$renderer, $$props) { ... }
 *
 * We transform it to:
 *
 *   import * as $ from 'svelte/internal/server';
 *   function Invoice($$renderer, $$props) { ... }   ← export default removed
 *   ... runtime imports ...
 *   export async function render(props = {}) { ... }
 */
function buildRenderWrapper(compiledCode: string, filePath: string): string {
	// ── Extract the component function name ────────────────────────────────
	//
	// The Svelte 5 server compiler consistently outputs:
	//   export default function ComponentName($$renderer, $$props) { ... }
	//
	// We need the name so we can reference it inside render().
	const nameMatch = compiledCode.match(/export default function (\w+)/);
	const componentName = nameMatch?.[1] ?? 'Component';

	// ── Strip the default export ───────────────────────────────────────────
	//
	// We remove `export default` from the component so it becomes a private
	// function. The module's public API is only the render() function we add.
	// This also avoids a situation where the module exports both `default`
	// (the raw component) and `render` (the PDF function) — we only want render.
	const componentCode = compiledCode.replace(
		/export default function (\w+)/,
		'function $1'
	);

	// ── Build the final module ─────────────────────────────────────────────
	//
	// We use string concatenation rather than a template literal for the
	// wrapper section so the indentation of the injected code is clean
	// and readable when inspected in Vite's module graph.
	return (
		componentCode +
		`
// ─── svelte-pdf render wrapper ───────────────────────────────────────────────
// Injected by the svelte-pdf Vite plugin.
// Source template: ${filePath}
//
// This wrapper ties together the full PDF rendering pipeline:
//   Svelte component → PDF AST → Yoga layout → PDFKit stream

import { render as __svelteRender } from 'svelte/server';
import { createDocument }  from 'svelte-pdf/runtime/document.js';
import { loadResources }   from 'svelte-pdf/runtime/resources.js';
import { computeLayout }   from 'svelte-pdf/layout/layout.js';
import { paginate }        from 'svelte-pdf/pagination/paginate.js';
import { renderPDF }       from 'svelte-pdf/renderer/render.js';

/**
 * Renders this template as a PDF.
 *
 * @param props - Props to pass to the <${componentName}> component.
 * @returns A Node.js Readable stream containing PDF data.
 *
 * @example SvelteKit route (adapter-node):
 *   export async function GET() {
 *     const pdf = await render({ invoice });
 *     return new Response(pdf, { headers: { 'Content-Type': 'application/pdf' } });
 *   }
 *
 * @example Write to file:
 *   const pdf = await render({ invoice });
 *   pdf.pipe(fs.createWriteStream('invoice.pdf'));
 */
export async function render(props = {}) {
  // Create a fresh, isolated document context for this render call.
  // Each call to render() gets its own DocumentContext, so concurrent
  // server requests can never interfere with each other.
  const doc = createDocument();

  // ── Pass 1: Execute the Svelte component tree ──────────────────────────
  //
  // Calling svelteRender() builds the PDF node tree as a side effect:
  // each component calls getContext('__pdf__') to find its parent node,
  // appends itself as a child, then calls setContext('__pdf__', ownNode)
  // so its own children see it as their parent.
  //
  // IMPORTANT: render() from svelte/server is lazy — it returns an object
  // with a getter for .html that triggers actual execution only when accessed.
  // We must access .html immediately or the component tree never runs.
  const { html: _ } = __svelteRender(${componentName}, {
    props,
    context: new Map([
      // Current parent node. Components read this, append themselves, then
      // update it so their children see them as the new parent.
      ['__pdf__', doc],
      // The document root. Font and Image components need this to declare
      // their resources, regardless of how deep they are in the tree.
      ['__pdf_root__', doc],
    ]),
  });

  // ── Async phase: load declared resources ───────────────────────────────
  //
  // Font and Image components declared their resources during Pass 1 by
  // pushing entries to doc.resources. We now load them all in parallel.
  //
  // This must complete before layout because Yoga's text measurement
  // callback uses PDFKit font metrics, which require loaded font data.
  await loadResources(doc.resources);

  // ── Pass 2: Compute Yoga flexbox layout ────────────────────────────────
  //
  // Assigns .layout = { x, y, width, height } to every node in the tree.
  // Absolute page coordinates, ready for PDFKit to draw at.
  computeLayout(doc);

  // Split the laid-out tree into pages (one PDFKit page per <Page> node).
  const pages = paginate(doc);

  // Render to a PDFKit stream and return it.
  // PDFDocument extends Node.js Readable, so callers can pipe it directly.
  // doc.resources carries the font entries so renderPDF can register custom
  // fonts on the PDFKit document before drawing begins.
  return renderPDF(pages, doc.resources, doc.metadata);
}
`
	);
}
